/** Central indexable route list for prerender + sitemap. Keep in sync with App.jsx. */
export const SITE_ORIGIN = "https://melangedigital.co";

/** Static tourism / DMA landing (synced folder). Canonical has no trailing slash. */
export const DESTINATION_LANDING = "/destination-marketing-agency";

export const routes = [
  "/",
  DESTINATION_LANDING,
  "/services",
  "/work",
  "/about",
  "/contact",
  "/blogs",
  "/careers",
  "/terms-of-service",
  "/privacy-policy",
  "/cancellation-and-refund-policy",
  "/cookie-policy",
  "/performance-marketing",
  "/work/zee5",
  "/work/costa-cruises",
  "/work/kalon",
  "/work/duvon",
  "/work/make-my-trip",
  "/work/sportz-village",
  "/work/active-club",
  "/work/kunal-rathod",
  "/work/sportz-village-xp",
  "/work/proportunity",
  "/work/dhruvak",
  "/work/travel-stop",
  "/work/genvr",
  "/work/rock-highland",
  "/work/aartech-solonics",
  "/work/enerqual",
  "/work/resorts-world-cruises",
  "/work/ganga-fashions",
  "/work/versailles-dental-clinic",
  "/work/healthy-mithai",
  "/work/jewel-houze",
  "/work/neotraders",
  "/work/devboost",
  "/work/singapore-tourism-board",
  "/work/her-hk",
  "/work/akbar-travels",
  "/work/zambia-tourism",
  "/work/navi-savi",
  "/services/brand-strategy",
  "/services/influencer-marketing",
  "/services/immersive-brand-storytelling",
  "/services/design-and-development",
  "/services/content-strategy-and-production",
  "/services/pr-and-outreach",
  "/services/content-marketing",
  "/services/ecommerce",
  "/services/design-solutions",
  "/services/performance-marketing",
  "/services/website-development-seo",
  "/services/brand-strategy/market-research",
  "/services/brand-strategy/brand-audit",
  "/services/brand-strategy/competition-category-benchmarking",
  "/services/brand-strategy/audience-profiling",
  "/services/brand-strategy/brand-experience",
  "/services/brand-strategy/communication-design",
  "/services/design-solutions/branding",
  "/services/design-solutions/graphic-design",
  "/services/design-solutions/data-visualization",
  "/services/content-marketing/social-media",
  "/services/content-marketing/influencer-marketing",
  "/services/content-marketing/video-graphy",
  "/services/content-marketing/photo-graphy",
  "/services/content-marketing/motion-graphics",
  "/services/content-marketing/articles",
  "/services/content-marketing/ad-copywriting",
  "/services/content-marketing/b2b-marketing",
  "/services/performance-marketing/ads",
  "/services/performance-marketing/media-buying-planning",
  "/services/performance-marketing/automation",
  "/services/performance-marketing/analytics",
  "/services/website-development-seo/web-development",
  "/services/website-development-seo/ui-ux",
  "/services/website-development-seo/content",
  "/services/website-development-seo/seo",
  "/services/ecommerce/market-research",
  "/services/ecommerce/d2c",
  "/services/ecommerce/marketplace-management",
  "/services/ecommerce/paid-campaigns",
  "/blogs/the-rise-of-creator-storefronts-and-how-they-are-reshaping-brand-influencer-partnerships",
  "/blogs/sustainable-design-and-packaging-why-2025-consumers-judge-before-they-click-buy",
  "/blogs/community-first-content-stacks-why-owning-your-audience-is-the-new-moat",
  "/blogs/from-products-to-experiences-how-micro-events-and-community-activations-are-shaping-brand-ip-in-2025",
  "/singapore-tourism",
  "/singapore-tourism-aeo-seo",
  "/siam-malls",
  "/work/green-label",
  "/ganga-fashion",
  "/work/maison-luxe",
  "/work/veda-naturals",
  "/services/aeo-seo",
];

/** Puppeteer prerender skips the static DMA folder (already real HTML from sync). */
export const prerenderRoutes = routes.filter((r) => r !== DESTINATION_LANDING);
